print('What do you get when you cross a snowman with a vampyre?')
input()
print('Frostbite!')
print()
print('What do dentists call an astronaut\'s cavity?')
input()
print('A black hole!')
print()
print('Knock knock.')
input()
print("Who's there?")
input() 
print('Interupting cow.')
input()
print('Interrupting cow wh', end='')
print('-MOO!')